baseURL = 'https://la-commitments.de/'
languageCode = 'de-de'
title = 'LA-C'
description = 'Die LA-Commitments'
theme = 'ananke'
sectionPagesMenu = 'main'

[params]
  custom_css = ["css/custom.css"]

